language: shell
os: linux
dist: bionic

services:
  - docker

script:
  - docker build -t $DOCKER_REPO .

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE ~= /^(cron|api)$/
