language: shell
os: linux
dist: bionic

services:
  - docker

script:
  - bash build

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
    condition: $TRAVIS_EVENT_TYPE = cron
